# 头部菜单，title: link
menu:
  Whoami: /whoami
  Github: https://github.com/cMc-Enhancer
  Bilibili: https://space.bilibili.com/6988477
  分类: /categories
  归档: /archives
  标签云: /tags

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:
  - http://music.163.com/song/media/outer/url?id=528484544.mp3
  - http://music.163.com/song/media/outer/url?id=33111211.mp3
  - http://music.163.com/song/media/outer/url?id=526101400.mp3
  - http://music.163.com/song/media/outer/url?id=32272663.mp3
  - http://music.163.com/song/media/outer/url?id=526103091.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '950f83c861604d6a6bd3'
    # 应用秘钥
    clientSecret: 'eb99ef07f83ce12506511020ff04384b35e3f201'
    # issue仓库名
    repo: 'cMc-Enhancer.github.io'
    # Github名
    owner: 'cMc-Enhancer'
    # Github名
    admin: ['cMc-Enhancer']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Enhancer

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-139406135-1

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
